version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: [ "python", "server.py" ]
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: [ "python", "client.py" ]
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:


